name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.1.0'
          java: 'java11'
      - name: Install native-image component
        run: gu install native-image
      - name: Build
        run: |
          mvn -B -ntp -Pnative package
          docker build -f src/main/docker/Dockerfile.native -t registry.heroku.com/xunit-reporter/web
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          heroku container:login
          docker push registry.heroku.com/xunit-reporter/web
          heroku container:release web -a xunit-reporter
